# 头部菜单，title: link
menu:
  首页: ''
  分类: /categories
  归档: /archives
  标签: /tags
  Github: https://github.com/AaronBank

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - https://hexo-shen.oss-cn-beijing.aliyuncs.com/lip/BEYOND%20-%20%E6%8A%A5%E7%AD%94%E4%B8%80%E7%94%9F.mp3
  - https://hexo-shen.oss-cn-beijing.aliyuncs.com/lip/BEYOND%20-%20%E5%8F%AF%E5%90%A6%E5%86%B2%E7%A0%B4.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: 'ee3640920c5ec2f34694'
    # 应用秘钥
    clientSecret: '31ca17ca1df0813e0513ab2b0868b94cdeec4ced'
    # issue仓库名
    repo: 'aaronbank.github.io'
    # Github名
    owner: 'aaronbank'
    # Github名
    admin: 'aaronbank'
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: true

# 网站关键字
keywords: 漫步者博客

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/logo.png

# rss文件
rss: atom.xml
